import { Suspense } from "react";

import AntdClientLocale from "@/components/AntdClientLocale";
import NProgressClient from "@/components/NProgressClient";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import zhCN from "antd/locale/zh_CN";
import "dayjs/locale/zh-cn";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "nprogress/nprogress.css";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "KM Dashboard",
  description: "Generated by lvg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ConfigProvider locale={zhCN}>
          <AntdRegistry>
            <AntdClientLocale />
            <Suspense fallback={null}>
              <NProgressClient />
            </Suspense>
            {children}
          </AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
